SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WF_SiteExtensions](
	[SiteId] [uniqueidentifier] NOT NULL,
	[InspectionDailyReportWorkgroupId] [uniqueidentifier] NULL,
	[LastDailyReportDate] [datetime2](7) NULL,
 CONSTRAINT [PK_WF_SiteExtensions] PRIMARY KEY CLUSTERED 
(
	[SiteId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
