SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WF_TicketAsset](
	[Id] [uniqueidentifier] NOT NULL,
	[TicketId] [uniqueidentifier] NOT NULL,
	[AssetId] [uniqueidentifier] NOT NULL,
	[AssetCategoryId] [uniqueidentifier] NOT NULL,
	[AssetName] [nvarchar](60) NOT NULL,
 CONSTRAINT [PK_WF_TicketAssets] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[WF_TicketAsset]  WITH CHECK ADD  CONSTRAINT [FK_WF_TicketAsset_WF_Ticket] FOREIGN KEY([TicketId])
REFERENCES [dbo].[WF_Ticket] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[WF_TicketAsset] CHECK CONSTRAINT [FK_WF_TicketAsset_WF_Ticket]
GO