SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WF_TicketTask](
	[Id] [uniqueidentifier] NOT NULL,
	[TicketId] [uniqueidentifier] NOT NULL,
	[TaskName] [nvarchar](50) NOT NULL,
	[IsCompleted] [bit] NOT NULL,
 CONSTRAINT [PK_WF_TicketTask] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[WF_TicketTask]  WITH CHECK ADD  CONSTRAINT [FK_WF_TicketTask_WF_Ticket] FOREIGN KEY([TicketId])
REFERENCES [dbo].[WF_Ticket] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[WF_TicketTask] CHECK CONSTRAINT [FK_WF_TicketTask_WF_Ticket]
GO