IF NOT EXISTS(SELECT 1
  FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME = 'WF_Ticket'
   AND TABLE_SCHEMA = 'dbo'
   AND COLUMN_NAME = 'Description'
   AND CHARACTER_MAXIMUM_LENGTH = -1) -- (CHARACTER_MAXIMUM_LENGTH == -1) == MAX
BEGIN
ALTER TABLE [dbo].[WF_Ticket] ALTER COLUMN Description nvarchar(max) not null
END

IF NOT EXISTS(SELECT 1
  FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME = 'WF_Ticket'
   AND TABLE_SCHEMA = 'dbo'
   AND COLUMN_NAME = 'Cause'
   AND CHARACTER_MAXIMUM_LENGTH = -1) -- (CHARACTER_MAXIMUM_LENGTH == -1) == MAX
BEGIN
ALTER TABLE [dbo].[WF_Ticket] ALTER COLUMN Cause nvarchar(max) not null
END

IF NOT EXISTS(SELECT 1
  FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME = 'WF_Ticket'
   AND TABLE_SCHEMA = 'dbo'
   AND COLUMN_NAME = 'Solution'
   AND CHARACTER_MAXIMUM_LENGTH = -1) -- (CHARACTER_MAXIMUM_LENGTH == -1) == MAX
BEGIN
ALTER TABLE [dbo].[WF_Ticket] ALTER COLUMN Solution nvarchar(max) not null
END

IF NOT EXISTS(SELECT 1
  FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME = 'WF_Ticket'
   AND TABLE_SCHEMA = 'dbo'
   AND COLUMN_NAME = 'Summary'
   AND CHARACTER_MAXIMUM_LENGTH = -1) -- (CHARACTER_MAXIMUM_LENGTH == -1) == MAX
BEGIN
ALTER TABLE [dbo].[WF_Ticket] ALTER COLUMN Summary nvarchar(max) not null
END

IF NOT EXISTS(SELECT 1
  FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME = 'WF_Ticket'
   AND TABLE_SCHEMA = 'dbo'
   AND COLUMN_NAME = 'Notes'
   AND CHARACTER_MAXIMUM_LENGTH = -1) -- (CHARACTER_MAXIMUM_LENGTH == -1) == MAX
BEGIN
ALTER TABLE [dbo].[WF_Ticket] ALTER COLUMN Notes nvarchar(max) not null
END

IF NOT EXISTS(SELECT 1
  FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME = 'WF_TicketTemplate'
   AND TABLE_SCHEMA = 'dbo'
   AND COLUMN_NAME = 'Summary'
   AND CHARACTER_MAXIMUM_LENGTH = -1) -- (CHARACTER_MAXIMUM_LENGTH == -1) == MAX
BEGIN
ALTER TABLE [dbo].[WF_TicketTemplate] ALTER COLUMN Summary nvarchar(max) not null
END

