IF NOT EXISTS (
SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME =N'WF_Ticket' 
AND TABLE_SCHEMA = N'dbo'
AND COLUMN_NAME = N'IssueName'
AND CHARACTER_MAXIMUM_LENGTH = 450
)
BEGIN 
ALTER TABLE [dbo].[WF_Ticket]
ALTER COLUMN IssueName nvarchar(450) NOT NULL
END;
