/* eslint-disable import/no-extraneous-dependencies */
import { rest } from 'msw'

export const mockedInsights = {
  insights: {
    before: 0,
    after: 0,
    items: [
      {
        id: 'c1741f9f-e6a2-401c-8e51-05b2de263b5a',
        siteId: 'a6b78f54-9875-47bc-9612-aa991cc464f3',
        sequenceNumber: 'INV1236PHI-I-40',
        floorCode: 'L2',
        equipmentId: 'fba1309b-3202-4299-b3b2-e66470d89180',
        twinId: 'INV-126PS-EAF-L02-01',
        type: 'note',
        name: '2 HOUR SET 1 COMPLETED WITH INSIGHTS',
        priority: 3,
        status: 'inProgress',
        lastStatus: 'readyToResolve',
        state: 'active',
        sourceType: 'inspection',
        occurredDate: '2022-12-04T22:10:53.401Z',
        updatedDate: '2023-11-08T19:57:53.748Z',
        externalId: '',
        occurrenceCount: 1,
        sourceName: 'Inspection',
        floorId: 'ae0c8ec1-d277-45b7-aabb-5f81bb948118',
        impactScores: [
          {
            fieldId: 'daily_avoidable_energy',
            name: 'Daily Avoidable Energy',
            value: 10,
            unit: 'kWh',
          },
          {
            fieldId: 'priority',
            name: 'Priority',
            value: 0,
            unit: '',
          },
          {
            fieldId: 'daily_avoidable_cost',
            name: 'Daily Avoidable Cost',
            value: 5,
            unit: 'USD',
          },
        ],
        equipmentName: 'EAF-L02-01',
        primaryModelId: 'dtmi:com:willowinc:Asset;1',
        ticketCount: 7,
        newOccurrence: false,
        ecmDependency: false,
        previouslyIgnored: 1,
        previouslyResolved: 1,
        previouslyResolvedAndIgnoredCount: 2,
        lastResolvedDate: '2023-08-17T16:50:07.196Z',
        lastIgnoredDate: '2023-08-17T16:51:12.019Z',
        reported: true,
      },
      {
        id: '891eba84-b740-47b1-9347-07afbbef600f',
        siteId: '404bd33c-a697-4027-b6a6-677e30a53d07',
        sequenceNumber: '60MP-I-246',
        floorCode: 'L8',
        equipmentId: '3efb5ad2-25f1-4200-baa1-e0d5234b54ca',
        twinId: 'INV-60MP-VAV-CN-L08-01',
        type: 'energy',
        name: 'VAV-CN-L08-01 List w',
        priority: 3,
        status: 'inProgress',
        lastStatus: 'inProgress',
        state: 'active',
        sourceType: 'inspection',
        occurredDate: '2023-11-05T00:00:00.000Z',
        updatedDate: '2023-11-01T20:15:28.221Z',
        externalId: '',
        occurrenceCount: 1,
        sourceName: 'Inspection',
        floorId: '7531c4ef-ac9e-4682-bf84-07b7f2c2230e',
        impactScores: [
          {
            fieldId: 'daily_avoidable_cost',
            name: 'Daily Avoidable Cost',
            value: 5,
            unit: 'USD',
          },
          {
            fieldId: 'priority',
            name: 'Priority',
            value: 0,
            unit: '',
          },
          {
            fieldId: 'daily_avoidable_energy',
            name: 'Daily Avoidable Energy',
            value: 10,
            unit: 'kWh',
          },
        ],
        equipmentName: 'VAV-CN-L08-01',
        ruleId: 'RuleId-Test-05',
        ruleName: 'Rule-Name-05',
        primaryModelId: 'dtmi:com:willowinc:Asset;1',
        ticketCount: 5,
        newOccurrence: false,
        ecmDependency: false,
        previouslyIgnored: 0,
        previouslyResolved: 0,
        previouslyResolvedAndIgnoredCount: 0,
        reported: true,
      },
    ],
    total: 2,
  },
  filters: {
    insightTypes: ['', 'Energy', 'Note'],
    sourceNames: [
      '{"sourceName":""}',
      '{"sourceName":"Willow Activate","sourceId":"7caed3b8-c0b6-4f91-ad3e-29d68882efeb"}',
    ],
    detailedStatus: ['New', 'Open', 'In Progress'],
    activity: ['Tickets'],
    primaryModelIds: ['dtmi:com:willowinc:Asset;1'],
  },
  impactScoreSummary: [
    {
      fieldId: 'daily_avoidable_cost',
      name: 'Daily Avoidable Cost',
      value: 163.57,
      unit: 'USD',
    },
    {
      fieldId: 'daily_avoidable_energy',
      name: 'Daily Avoidable Energy',
      value: 10.41,
      unit: 'kWh',
    },
  ],
}

export const handlers = [
  rest.post('/:region/api/insights/all', (req, res, ctx) =>
    res(ctx.delay(0), ctx.json(mockedInsights))
  ),
]
