export default [
  {
    id: '64d8ab8a-a714-58ca-e087-745cbc800908',
    name: 'Electrical Building Component',
    childCategories: [
      {
        id: '36de809a-399f-51d4-8e11-9b63b2e609be',
        name: 'Electrical Circuit',
        childCategories: [
          {
            id: '9bf1d020-515d-2160-0819-7a63bba2aae2',
            name: 'Electrical Circuit 3-Pole',
            childCategories: [],
            assetCount: 11,
            hasChildren: true,
          },
        ],
        assetCount: 0,
        hasChildren: true,
      },
    ],
    assetCount: 0,
    hasChildren: true,
  },
  {
    id: 'f209dde3-7286-01ab-ddf5-c8042a71714e',
    name: 'Equipment',
    childCategories: [
      {
        id: '8d4cce11-5d47-d2a0-5f1a-3057305e337a',
        name: 'Conveyance Equipment',
        childCategories: [
          {
            id: 'fe8f5743-a382-7ffa-9213-70e5e0d493f6',
            name: 'Elevator',
            childCategories: [],
            assetCount: 1,
            hasChildren: true,
          },
        ],
        assetCount: 0,
        hasChildren: true,
      },
      {
        id: '22327310-8b85-fbc6-ff48-a99708e6eb04',
        name: 'Electrical Equipment',
        childCategories: [
          {
            id: 'be3cc2fd-0573-640f-3e61-58e022bd7f37',
            name: 'Electrical Distribution Equipment',
            childCategories: [
              {
                id: '45edbd24-8dc3-4926-e399-2755532e9dca',
                name: 'Disconnect Switch',
                childCategories: [],
                assetCount: 62,
                hasChildren: true,
              },
              {
                id: '5c5aaea0-bed9-067b-0f0d-266f9d5234aa',
                name: 'Electrical Panelboard',
                childCategories: [
                  {
                    id: '3c9f5169-4b8d-be0d-79f9-df0767c68d18',
                    name: 'Electrical Panelboard MCB',
                    childCategories: [],
                    assetCount: 62,
                    hasChildren: true,
                  },
                  {
                    id: '2a594878-227a-9d8d-aead-0112961ece36',
                    name: 'Electrical Panelboard MLO',
                    childCategories: [],
                    assetCount: 62,
                    hasChildren: true,
                  },
                ],
                assetCount: 24,
                hasChildren: true,
              },
              {
                id: '448ccef5-c344-3328-d8e2-efb4b2b5f30c',
                name: 'Switchgear',
                childCategories: [],
                assetCount: 6,
                hasChildren: true,
              },
              {
                id: 'cb8ee4f8-446f-4daf-fe80-b5146f26ba6d',
                name: 'Transfer Switch',
                childCategories: [
                  {
                    id: '6d9fed8e-94c2-0e88-4346-a24e89fe5875',
                    name: 'Automatic Transfer Switch',
                    childCategories: [],
                    assetCount: 26,
                    hasChildren: true,
                  },
                ],
                assetCount: 0,
                hasChildren: true,
              },
            ],
            assetCount: 0,
            hasChildren: true,
          },
          {
            id: '9359d40d-f811-530b-cf7c-7cba1e3a146c',
            name: 'Electrical Generation & Storage Equipment',
            childCategories: [
              {
                id: '1f258eea-866d-046a-9581-a5bad993d480',
                name: 'UPS',
                childCategories: [],
                assetCount: 4,
                hasChildren: true,
              },
              {
                id: 'fb11039e-cac9-fc59-14c1-58c50326dd5e',
                name: 'Generator',
                childCategories: [
                  {
                    id: '57f85922-113e-8789-07c9-061797181f02',
                    name: 'Cogenerator',
                    childCategories: [],
                    assetCount: 1,
                    hasChildren: true,
                  },
                ],
                assetCount: 4,
                hasChildren: true,
              },
            ],
            assetCount: 0,
            hasChildren: true,
          },
        ],
        assetCount: 0,
        hasChildren: true,
      },
      {
        id: '801246d7-68dc-a300-b9ec-d6d8b3002b7e',
        name: 'Fire Protection Equipment',
        childCategories: [
          {
            id: '315dea43-4e2a-fb75-a424-6a0487ef19e6',
            name: 'Fire Suppression Equipment',
            childCategories: [
              {
                id: '6f02a593-ac87-8013-9650-8e213fe56ad2',
                name: 'Sprinkler Equipment',
                childCategories: [
                  {
                    id: '71fa0791-2c4a-35a0-1ec4-f6b5788d42d6',
                    name: 'Fire Pump',
                    childCategories: [],
                    assetCount: 5,
                    hasChildren: true,
                  },
                  {
                    id: 'c9bdb9f6-fe56-aff6-5aa8-a74d4686736f',
                    name: 'Sprinkler Tank',
                    childCategories: [],
                    assetCount: 6,
                    hasChildren: true,
                  },
                ],
                assetCount: 0,
                hasChildren: true,
              },
            ],
            assetCount: 0,
            hasChildren: true,
          },
        ],
        assetCount: 0,
        hasChildren: true,
      },
      {
        id: 'db4ce947-73fa-b616-5e18-4f15164b81bd',
        name: 'HVAC Equipment',
        childCategories: [
          {
            id: 'b8462439-711f-31a9-51c9-bd2ecce49919',
            name: 'Air Filter',
            childCategories: [],
            assetCount: 1,
            hasChildren: true,
          },
          {
            id: 'f48ae3e2-cc30-cda4-8b9c-867d9711563e',
            name: 'Chiller',
            childCategories: [],
            assetCount: 6,
            hasChildren: true,
          },
          {
            id: 'e9794ccb-ffaa-5fa5-39ca-d017fee6ba2f',
            name: 'Cooling Tower',
            childCategories: [],
            assetCount: 6,
            hasChildren: true,
          },
          {
            id: '018abcef-04c2-f855-d0d5-2f21fd102699',
            name: 'Heat Exchanger',
            childCategories: [],
            assetCount: 19,
            hasChildren: true,
          },
          {
            id: '454b9c2e-e3c9-8a10-694d-4a7c938ebe70',
            name: 'Air Handling Unit',
            childCategories: [],
            assetCount: 152,
            hasChildren: true,
          },
          {
            id: '24593f47-3766-8414-a7fe-2531752c1f75',
            name: 'Fan',
            childCategories: [
              {
                id: '9e40630b-7d1b-d270-c088-c6f7073b1713',
                name: 'Exhaust Fan',
                childCategories: [],
                assetCount: 91,
                hasChildren: true,
              },
              {
                id: '0aa62e87-4b59-08c6-ec4e-44b3b2d9629a',
                name: 'Stair Pressurization Fan',
                childCategories: [],
                assetCount: 10,
                hasChildren: true,
              },
              {
                id: 'ab046de2-e039-d545-45fc-408230de4ef7',
                name: 'Supply Fan',
                childCategories: [],
                assetCount: 13,
                hasChildren: true,
              },
            ],
            assetCount: 0,
            hasChildren: true,
          },
          {
            id: 'e4c5b553-3a50-c374-e6a5-25fed5fd0e29',
            name: 'HVAC Pump',
            childCategories: [],
            assetCount: 37,
            hasChildren: true,
          },
          {
            id: '2194a459-78c3-5a7c-4900-c90d6e9e5f79',
            name: 'HVAC Tank',
            childCategories: [],
            assetCount: 3,
            hasChildren: true,
          },
          {
            id: 'f4b54cbd-3f6a-f2d0-e54e-c2fa1befdb6c',
            name: 'Terminal Unit',
            childCategories: [
              {
                id: '0cfc721b-d61c-55ad-551c-ec7b204c9a61',
                name: 'CAV Box',
                childCategories: [],
                assetCount: 9,
                hasChildren: true,
              },
              {
                id: '8162f53f-1971-ee40-001f-c276aad20ba0',
                name: 'VAV Box',
                childCategories: [],
                assetCount: 45,
                hasChildren: true,
              },
            ],
            assetCount: 0,
            hasChildren: true,
          },
          {
            id: '08b3782f-597a-1d5a-1755-83e8cf41eb1d',
            name: 'HVAC Valve',
            childCategories: [
              {
                id: 'df1075d7-9cb6-5e75-bdb7-28b611c6b565',
                name: 'Pressure Reducing Station',
                childCategories: [],
                assetCount: 1,
                hasChildren: true,
              },
            ],
            assetCount: 2,
            hasChildren: true,
          },
        ],
        assetCount: 0,
        hasChildren: true,
      },
      {
        id: 'fb1e5cf1-bfce-ff3b-932c-944717d7a202',
        name: 'ICT Equipment',
        childCategories: [
          {
            id: '9acdf828-9ae3-c9d2-b2e0-961754d98274',
            name: 'Controller',
            childCategories: [
              {
                id: 'e9eeda45-aa92-0079-f926-04da51997be2',
                name: 'BACnet Controller',
                childCategories: [],
                assetCount: 94,
                hasChildren: true,
              },
              {
                id: '25e8f8af-2516-4eab-1afe-4c0a41cdc833',
                name: 'Modbus Controller',
                childCategories: [],
                assetCount: 2,
                hasChildren: true,
              },
            ],
            assetCount: 35,
            hasChildren: true,
          },
          {
            id: 'e2fba81d-9582-07e4-84c5-f16fb470be5b',
            name: 'Sensor Equipment',
            childCategories: [
              {
                id: '3e500f96-5cef-32ea-356f-a087365513a2',
                name: 'Occupancy Sensor',
                childCategories: [],
                assetCount: 2,
                hasChildren: true,
              },
              {
                id: 'c1e124a1-0e8c-af44-8689-10b698515cab',
                name: 'Vibration Sensor',
                childCategories: [],
                assetCount: 1,
                hasChildren: true,
              },
              {
                id: 'b4b7747e-5865-3d5e-4c57-9f7392c8f19e',
                name: 'People Count Sensor',
                childCategories: [],
                assetCount: 5,
                hasChildren: true,
              },
            ],
            assetCount: 3,
            hasChildren: true,
          },
        ],
        assetCount: 0,
        hasChildren: true,
      },
      {
        id: '2ae8c50f-3f69-9a1d-96d5-aeaf3c3ad096',
        name: 'Meter Equipment',
        childCategories: [
          {
            id: '368b1f43-4296-da89-0058-939b0f0f02dc',
            name: 'Electrical Meter',
            childCategories: [],
            assetCount: 108,
            hasChildren: true,
          },
          {
            id: '90b1c19e-fb61-0fc4-c34b-356152e46a08',
            name: 'Gas Meter',
            childCategories: [],
            assetCount: 1,
            hasChildren: true,
          },
          {
            id: '247c9c83-59a6-bfd9-517a-a9875d59be44',
            name: 'Water Meter',
            childCategories: [],
            assetCount: 24,
            hasChildren: true,
          },
        ],
        assetCount: 0,
        hasChildren: true,
      },
      {
        id: 'ed92aaac-5354-376b-16d6-bb3a67e8dd1f',
        name: 'Plumbing Equipment',
        childCategories: [
          {
            id: '17ac9162-893a-0d01-fdc5-6384b36856fc',
            name: 'Plumbing Tank',
            childCategories: [
              {
                id: '36d86c73-5fe2-435e-98e4-fe6aa8b319a0',
                name: 'Expansion Tank',
                childCategories: [],
                assetCount: 7,
                hasChildren: true,
              },
            ],
            assetCount: 0,
            hasChildren: true,
          },
          {
            id: '37d1c690-20af-d3b0-2176-0f0b9bd66c55',
            name: 'Plumbing Pump',
            childCategories: [
              {
                id: '8f881372-7cb6-876d-a527-e22ac3338b50',
                name: 'Sump Pump',
                childCategories: [],
                assetCount: 3,
                hasChildren: true,
              },
            ],
            assetCount: 0,
            hasChildren: true,
          },
          {
            id: '5698e7a7-fcff-93c3-7bee-cbc55077e8b3',
            name: 'Water Heater',
            childCategories: [],
            assetCount: 61,
            hasChildren: true,
          },
          {
            id: 'bc204cfd-7e8e-97f1-1db5-6e292ce42be0',
            name: 'Water Treatment',
            childCategories: [
              {
                id: 'bc316633-845e-964f-7ea2-4d639fcc0a6d',
                name: 'Water Filtration',
                childCategories: [],
                assetCount: 1,
                hasChildren: true,
              },
            ],
            assetCount: 0,
            hasChildren: true,
          },
        ],
        assetCount: 0,
        hasChildren: true,
      },
    ],
    assetCount: 0,
    hasChildren: true,
  },
]
