import { rest } from 'msw'

export const timeZones = [
  {
    id: 'Dateline Standard Time',
    displayName: '(UTC-12:00) International Date Line West',
    offset: '-12:00',
    regionTimeZone: {
      '001': 'Etc/GMT+12',
      ZZ: 'Etc/GMT+12',
    },
  },
  {
    id: 'UTC-11',
    displayName: '(UTC-11:00) Coordinated Universal Time-11',
    offset: '-11:00',
    regionTimeZone: {
      '001': 'Etc/GMT+11',
      AS: 'Pacific/Pago_Pago',
      NU: 'Pacific/Niue',
      UM: 'Pacific/Midway',
      ZZ: 'Etc/GMT+11',
    },
  },
  {
    id: 'Aleutian Standard Time',
    displayName: '(UTC-10:00) Aleutian Islands',
    offset: '-10:00',
    regionTimeZone: {
      '001': 'America/Adak',
      US: 'America/Adak',
    },
  },
  {
    id: 'Hawaiian Standard Time',
    displayName: '(UTC-10:00) Hawaii',
    offset: '-10:00',
    regionTimeZone: {
      '001': 'Pacific/Honolulu',
      CK: 'Pacific/Rarotonga',
      PF: 'Pacific/Tahiti',
      UM: 'Pacific/Johnston',
      US: 'Pacific/Honolulu',
      ZZ: 'Etc/GMT+10',
    },
  },
  {
    id: 'Marquesas Standard Time',
    displayName: '(UTC-09:30) Marquesas Islands',
    offset: '-09:30',
    regionTimeZone: {
      '001': 'Pacific/Marquesas',
      PF: 'Pacific/Marquesas',
    },
  },
  {
    id: 'Alaskan Standard Time',
    displayName: '(UTC-09:00) Alaska',
    offset: '-09:00',
    regionTimeZone: {
      '001': 'America/Anchorage',
      US: 'America/Anchorage America/Juneau America/Nome America/Sitka America/Yakutat',
    },
  },
  {
    id: 'UTC-09',
    displayName: '(UTC-09:00) Coordinated Universal Time-09',
    offset: '-09:00',
    regionTimeZone: {
      '001': 'Etc/GMT+9',
      PF: 'Pacific/Gambier',
      ZZ: 'Etc/GMT+9',
    },
  },
  {
    id: 'Pacific Standard Time (Mexico)',
    displayName: '(UTC-08:00) Baja California',
    offset: '-08:00',
    regionTimeZone: {
      '001': 'America/Tijuana',
      MX: 'America/Tijuana America/Santa_Isabel',
    },
  },
  {
    id: 'UTC-08',
    displayName: '(UTC-08:00) Coordinated Universal Time-08',
    offset: '-08:00',
    regionTimeZone: {
      '001': 'Etc/GMT+8',
      PN: 'Pacific/Pitcairn',
      ZZ: 'Etc/GMT+8',
    },
  },
  {
    id: 'Pacific Standard Time',
    displayName: '(UTC-08:00) Pacific Time (US & Canada)',
    offset: '-08:00',
    regionTimeZone: {
      '001': 'America/Los_Angeles',
      CA: 'America/Vancouver America/Dawson America/Whitehorse',
      US: 'America/Los_Angeles America/Metlakatla',
      ZZ: 'PST8PDT',
    },
  },
  {
    id: 'US Mountain Standard Time',
    displayName: '(UTC-07:00) Arizona',
    offset: '-07:00',
    regionTimeZone: {
      '001': 'America/Phoenix',
      CA: 'America/Dawson_Creek America/Creston America/Fort_Nelson',
      MX: 'America/Hermosillo',
      US: 'America/Phoenix',
      ZZ: 'Etc/GMT+7',
    },
  },
  {
    id: 'Mountain Standard Time (Mexico)',
    displayName: '(UTC-07:00) Chihuahua, La Paz, Mazatlan',
    offset: '-07:00',
    regionTimeZone: {
      '001': 'America/Chihuahua',
      MX: 'America/Chihuahua America/Mazatlan',
    },
  },
  {
    id: 'Mountain Standard Time',
    displayName: '(UTC-07:00) Mountain Time (US & Canada)',
    offset: '-07:00',
    regionTimeZone: {
      '001': 'America/Denver',
      CA: 'America/Edmonton America/Cambridge_Bay America/Inuvik America/Yellowknife',
      MX: 'America/Ojinaga',
      US: 'America/Denver America/Boise',
      ZZ: 'MST7MDT',
    },
  },
  {
    id: 'Yukon Standard Time',
    displayName: '(UTC-07:00) Yukon',
    offset: '-07:00',
  },
  {
    id: 'Central America Standard Time',
    displayName: '(UTC-06:00) Central America',
    offset: '-06:00',
    regionTimeZone: {
      '001': 'America/Guatemala',
      BZ: 'America/Belize',
      CR: 'America/Costa_Rica',
      EC: 'Pacific/Galapagos',
      GT: 'America/Guatemala',
      HN: 'America/Tegucigalpa',
      NI: 'America/Managua',
      SV: 'America/El_Salvador',
      ZZ: 'Etc/GMT+6',
    },
  },
  {
    id: 'Central Standard Time',
    displayName: '(UTC-06:00) Central Time (US & Canada)',
    offset: '-06:00',
    regionTimeZone: {
      '001': 'America/Chicago',
      CA: 'America/Winnipeg America/Rainy_River America/Rankin_Inlet America/Resolute',
      MX: 'America/Matamoros',
      US: 'America/Chicago America/Indiana/Knox America/Indiana/Tell_City America/Menominee America/North_Dakota/Beulah America/North_Dakota/Center America/North_Dakota/New_Salem',
      ZZ: 'CST6CDT',
    },
  },
  {
    id: 'Easter Island Standard Time',
    displayName: '(UTC-06:00) Easter Island',
    offset: '-06:00',
    regionTimeZone: {
      '001': 'Pacific/Easter',
      CL: 'Pacific/Easter',
    },
  },
  {
    id: 'Central Standard Time (Mexico)',
    displayName: '(UTC-06:00) Guadalajara, Mexico City, Monterrey',
    offset: '-06:00',
    regionTimeZone: {
      '001': 'America/Mexico_City',
      MX: 'America/Mexico_City America/Bahia_Banderas America/Merida America/Monterrey',
    },
  },
  {
    id: 'Canada Central Standard Time',
    displayName: '(UTC-06:00) Saskatchewan',
    offset: '-06:00',
    regionTimeZone: {
      '001': 'America/Regina',
      CA: 'America/Regina America/Swift_Current',
    },
  },
  {
    id: 'SA Pacific Standard Time',
    displayName: '(UTC-05:00) Bogota, Lima, Quito, Rio Branco',
    offset: '-05:00',
    regionTimeZone: {
      '001': 'America/Bogota',
      BR: 'America/Rio_Branco America/Eirunepe',
      CA: 'America/Coral_Harbour',
      CO: 'America/Bogota',
      EC: 'America/Guayaquil',
      JM: 'America/Jamaica',
      KY: 'America/Cayman',
      PA: 'America/Panama',
      PE: 'America/Lima',
      ZZ: 'Etc/GMT+5',
    },
  },
  {
    id: 'Eastern Standard Time (Mexico)',
    displayName: '(UTC-05:00) Chetumal',
    offset: '-05:00',
    regionTimeZone: {
      '001': 'America/Cancun',
      MX: 'America/Cancun',
    },
  },
  {
    id: 'Eastern Standard Time',
    displayName: '(UTC-05:00) Eastern Time (US & Canada)',
    offset: '-05:00',
    regionTimeZone: {
      '001': 'America/New_York',
      BS: 'America/Nassau',
      CA: 'America/Toronto America/Iqaluit America/Montreal America/Nipigon America/Pangnirtung America/Thunder_Bay',
      US: 'America/New_York America/Detroit America/Indiana/Petersburg America/Indiana/Vincennes America/Indiana/Winamac America/Kentucky/Monticello America/Louisville',
      ZZ: 'EST5EDT',
    },
  },
  {
    id: 'Haiti Standard Time',
    displayName: '(UTC-05:00) Haiti',
    offset: '-05:00',
    regionTimeZone: {
      '001': 'America/Port-au-Prince',
      HT: 'America/Port-au-Prince',
    },
  },
  {
    id: 'Cuba Standard Time',
    displayName: '(UTC-05:00) Havana',
    offset: '-05:00',
    regionTimeZone: {
      '001': 'America/Havana',
      CU: 'America/Havana',
    },
  },
  {
    id: 'US Eastern Standard Time',
    displayName: '(UTC-05:00) Indiana (East)',
    offset: '-05:00',
    regionTimeZone: {
      '001': 'America/Indianapolis',
      US: 'America/Indianapolis America/Indiana/Marengo America/Indiana/Vevay',
    },
  },
  {
    id: 'Turks And Caicos Standard Time',
    displayName: '(UTC-05:00) Turks and Caicos',
    offset: '-05:00',
    regionTimeZone: {
      '001': 'America/Grand_Turk',
      TC: 'America/Grand_Turk',
    },
  },
  {
    id: 'Paraguay Standard Time',
    displayName: '(UTC-04:00) Asuncion',
    offset: '-04:00',
    regionTimeZone: {
      '001': 'America/Asuncion',
      PY: 'America/Asuncion',
    },
  },
  {
    id: 'Atlantic Standard Time',
    displayName: '(UTC-04:00) Atlantic Time (Canada)',
    offset: '-04:00',
    regionTimeZone: {
      '001': 'America/Halifax',
      BM: 'Atlantic/Bermuda',
      CA: 'America/Halifax America/Glace_Bay America/Goose_Bay America/Moncton',
      GL: 'America/Thule',
    },
  },
  {
    id: 'Venezuela Standard Time',
    displayName: '(UTC-04:00) Caracas',
    offset: '-04:00',
    regionTimeZone: {
      '001': 'America/Caracas',
      VE: 'America/Caracas',
    },
  },
  {
    id: 'Central Brazilian Standard Time',
    displayName: '(UTC-04:00) Cuiaba',
    offset: '-04:00',
    regionTimeZone: {
      '001': 'America/Cuiaba',
      BR: 'America/Cuiaba America/Campo_Grande',
    },
  },
  {
    id: 'SA Western Standard Time',
    displayName: '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan',
    offset: '-04:00',
    regionTimeZone: {
      '001': 'America/La_Paz',
      AG: 'America/Antigua',
      AI: 'America/Anguilla',
      AW: 'America/Aruba',
      BB: 'America/Barbados',
      BL: 'America/St_Barthelemy',
      BO: 'America/La_Paz',
      BQ: 'America/Kralendijk',
      BR: 'America/Manaus America/Boa_Vista America/Porto_Velho',
      CA: 'America/Blanc-Sablon',
      CW: 'America/Curacao',
      DM: 'America/Dominica',
      DO: 'America/Santo_Domingo',
      GD: 'America/Grenada',
      GP: 'America/Guadeloupe',
      GY: 'America/Guyana',
      KN: 'America/St_Kitts',
      LC: 'America/St_Lucia',
      MF: 'America/Marigot',
      MQ: 'America/Martinique',
      MS: 'America/Montserrat',
      PR: 'America/Puerto_Rico',
      SX: 'America/Lower_Princes',
      TT: 'America/Port_of_Spain',
      VC: 'America/St_Vincent',
      VG: 'America/Tortola',
      VI: 'America/St_Thomas',
      ZZ: 'Etc/GMT+4',
    },
  },
  {
    id: 'Pacific SA Standard Time',
    displayName: '(UTC-04:00) Santiago',
    offset: '-04:00',
    regionTimeZone: {
      '001': 'America/Santiago',
      CL: 'America/Santiago',
    },
  },
  {
    id: 'Newfoundland Standard Time',
    displayName: '(UTC-03:30) Newfoundland',
    offset: '-03:30',
    regionTimeZone: {
      '001': 'America/St_Johns',
      CA: 'America/St_Johns',
    },
  },
  {
    id: 'Tocantins Standard Time',
    displayName: '(UTC-03:00) Araguaina',
    offset: '-03:00',
    regionTimeZone: {
      '001': 'America/Araguaina',
      BR: 'America/Araguaina',
    },
  },
  {
    id: 'E. South America Standard Time',
    displayName: '(UTC-03:00) Brasilia',
    offset: '-03:00',
    regionTimeZone: {
      '001': 'America/Sao_Paulo',
      BR: 'America/Sao_Paulo',
    },
  },
  {
    id: 'SA Eastern Standard Time',
    displayName: '(UTC-03:00) Cayenne, Fortaleza',
    offset: '-03:00',
    regionTimeZone: {
      '001': 'America/Cayenne',
      AQ: 'Antarctica/Rothera',
      BR: 'America/Fortaleza America/Belem America/Maceio America/Recife America/Santarem',
      FK: 'Atlantic/Stanley',
      GF: 'America/Cayenne',
      SR: 'America/Paramaribo',
      ZZ: 'Etc/GMT+3',
    },
  },
  {
    id: 'Argentina Standard Time',
    displayName: '(UTC-03:00) City of Buenos Aires',
    offset: '-03:00',
    regionTimeZone: {
      '001': 'America/Buenos_Aires',
      AR: 'America/Buenos_Aires America/Argentina/La_Rioja America/Argentina/Rio_Gallegos America/Argentina/Salta America/Argentina/San_Juan America/Argentina/San_Luis America/Argentina/Tucuman America/Argentina/Ushuaia America/Catamarca America/Cordoba America/Jujuy America/Mendoza',
    },
  },
  {
    id: 'Greenland Standard Time',
    displayName: '(UTC-03:00) Greenland',
    offset: '-03:00',
    regionTimeZone: {
      '001': 'America/Godthab',
      GL: 'America/Godthab',
    },
  },
  {
    id: 'Montevideo Standard Time',
    displayName: '(UTC-03:00) Montevideo',
    offset: '-03:00',
    regionTimeZone: {
      '001': 'America/Montevideo',
      UY: 'America/Montevideo',
    },
  },
  {
    id: 'Magallanes Standard Time',
    displayName: '(UTC-03:00) Punta Arenas',
    offset: '-03:00',
    regionTimeZone: {
      '001': 'America/Punta_Arenas',
      AQ: 'Antarctica/Palmer',
      CL: 'America/Punta_Arenas',
    },
  },
  {
    id: 'Saint Pierre Standard Time',
    displayName: '(UTC-03:00) Saint Pierre and Miquelon',
    offset: '-03:00',
    regionTimeZone: {
      '001': 'America/Miquelon',
      PM: 'America/Miquelon',
    },
  },
  {
    id: 'Bahia Standard Time',
    displayName: '(UTC-03:00) Salvador',
    offset: '-03:00',
    regionTimeZone: {
      '001': 'America/Bahia',
      BR: 'America/Bahia',
    },
  },
  {
    id: 'UTC-02',
    displayName: '(UTC-02:00) Coordinated Universal Time-02',
    offset: '-02:00',
    regionTimeZone: {
      '001': 'Etc/GMT+2',
      BR: 'America/Noronha',
      GS: 'Atlantic/South_Georgia',
      ZZ: 'Etc/GMT+2',
    },
  },
  {
    id: 'Mid-Atlantic Standard Time',
    displayName: '(UTC-02:00) Mid-Atlantic - Old',
    offset: '-02:00',
  },
  {
    id: 'Azores Standard Time',
    displayName: '(UTC-01:00) Azores',
    offset: '-01:00',
    regionTimeZone: {
      '001': 'Atlantic/Azores',
      GL: 'America/Scoresbysund',
      PT: 'Atlantic/Azores',
    },
  },
  {
    id: 'Cape Verde Standard Time',
    displayName: '(UTC-01:00) Cabo Verde Is.',
    offset: '-01:00',
    regionTimeZone: {
      '001': 'Atlantic/Cape_Verde',
      CV: 'Atlantic/Cape_Verde',
      ZZ: 'Etc/GMT+1',
    },
  },
  {
    id: 'UTC',
    displayName: '(UTC) Coordinated Universal Time',
    offset: '+00:00',
    regionTimeZone: {
      '001': 'Etc/GMT',
      GL: 'America/Danmarkshavn',
      ZZ: 'Etc/GMT Etc/UTC',
    },
  },
  {
    id: 'GMT Standard Time',
    displayName: '(UTC+00:00) Dublin, Edinburgh, Lisbon, London',
    offset: '+00:00',
    regionTimeZone: {
      '001': 'Europe/London',
      ES: 'Atlantic/Canary',
      FO: 'Atlantic/Faeroe',
      GB: 'Europe/London',
      GG: 'Europe/Guernsey',
      IE: 'Europe/Dublin',
      IM: 'Europe/Isle_of_Man',
      JE: 'Europe/Jersey',
      PT: 'Europe/Lisbon Atlantic/Madeira',
    },
  },
  {
    id: 'Greenwich Standard Time',
    displayName: '(UTC+00:00) Monrovia, Reykjavik',
    offset: '+00:00',
    regionTimeZone: {
      '001': 'Atlantic/Reykjavik',
      BF: 'Africa/Ouagadougou',
      CI: 'Africa/Abidjan',
      GH: 'Africa/Accra',
      GM: 'Africa/Banjul',
      GN: 'Africa/Conakry',
      GW: 'Africa/Bissau',
      IS: 'Atlantic/Reykjavik',
      LR: 'Africa/Monrovia',
      ML: 'Africa/Bamako',
      MR: 'Africa/Nouakchott',
      SH: 'Atlantic/St_Helena',
      SL: 'Africa/Freetown',
      SN: 'Africa/Dakar',
      TG: 'Africa/Lome',
    },
  },
  {
    id: 'Sao Tome Standard Time',
    displayName: '(UTC+00:00) Sao Tome',
    offset: '+00:00',
    regionTimeZone: {
      '001': 'Africa/Sao_Tome',
      ST: 'Africa/Sao_Tome',
    },
  },
  {
    id: 'Morocco Standard Time',
    displayName: '(UTC+01:00) Casablanca',
    offset: '+00:00',
    regionTimeZone: {
      '001': 'Africa/Casablanca',
      EH: 'Africa/El_Aaiun',
      MA: 'Africa/Casablanca',
    },
  },
  {
    id: 'W. Europe Standard Time',
    displayName: '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
    offset: '+01:00',
    regionTimeZone: {
      '001': 'Europe/Berlin',
      AD: 'Europe/Andorra',
      AT: 'Europe/Vienna',
      CH: 'Europe/Zurich',
      DE: 'Europe/Berlin Europe/Busingen',
      GI: 'Europe/Gibraltar',
      IT: 'Europe/Rome',
      LI: 'Europe/Vaduz',
      LU: 'Europe/Luxembourg',
      MC: 'Europe/Monaco',
      MT: 'Europe/Malta',
      NL: 'Europe/Amsterdam',
      NO: 'Europe/Oslo',
      SE: 'Europe/Stockholm',
      SJ: 'Arctic/Longyearbyen',
      SM: 'Europe/San_Marino',
      VA: 'Europe/Vatican',
    },
  },
  {
    id: 'Central Europe Standard Time',
    displayName:
      '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
    offset: '+01:00',
    regionTimeZone: {
      '001': 'Europe/Budapest',
      AL: 'Europe/Tirane',
      CZ: 'Europe/Prague',
      HU: 'Europe/Budapest',
      ME: 'Europe/Podgorica',
      RS: 'Europe/Belgrade',
      SI: 'Europe/Ljubljana',
      SK: 'Europe/Bratislava',
    },
  },
  {
    id: 'Romance Standard Time',
    displayName: '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',
    offset: '+01:00',
    regionTimeZone: {
      '001': 'Europe/Paris',
      BE: 'Europe/Brussels',
      DK: 'Europe/Copenhagen',
      ES: 'Europe/Madrid Africa/Ceuta',
      FR: 'Europe/Paris',
    },
  },
  {
    id: 'Central European Standard Time',
    displayName: '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
    offset: '+01:00',
    regionTimeZone: {
      '001': 'Europe/Warsaw',
      BA: 'Europe/Sarajevo',
      HR: 'Europe/Zagreb',
      MK: 'Europe/Skopje',
      PL: 'Europe/Warsaw',
    },
  },
  {
    id: 'W. Central Africa Standard Time',
    displayName: '(UTC+01:00) West Central Africa',
    offset: '+01:00',
    regionTimeZone: {
      '001': 'Africa/Lagos',
      AO: 'Africa/Luanda',
      BJ: 'Africa/Porto-Novo',
      CD: 'Africa/Kinshasa',
      CF: 'Africa/Bangui',
      CG: 'Africa/Brazzaville',
      CM: 'Africa/Douala',
      DZ: 'Africa/Algiers',
      GA: 'Africa/Libreville',
      GQ: 'Africa/Malabo',
      NE: 'Africa/Niamey',
      NG: 'Africa/Lagos',
      TD: 'Africa/Ndjamena',
      TN: 'Africa/Tunis',
      ZZ: 'Etc/GMT-1',
    },
  },
  {
    id: 'GTB Standard Time',
    displayName: '(UTC+02:00) Athens, Bucharest',
    offset: '+02:00',
    regionTimeZone: {
      '001': 'Europe/Bucharest',
      CY: 'Asia/Famagusta Asia/Nicosia',
      GR: 'Europe/Athens',
      RO: 'Europe/Bucharest',
    },
  },
  {
    id: 'Middle East Standard Time',
    displayName: '(UTC+02:00) Beirut',
    offset: '+02:00',
    regionTimeZone: {
      '001': 'Asia/Beirut',
      LB: 'Asia/Beirut',
    },
  },
  {
    id: 'Egypt Standard Time',
    displayName: '(UTC+02:00) Cairo',
    offset: '+02:00',
    regionTimeZone: {
      '001': 'Africa/Cairo',
      EG: 'Africa/Cairo',
    },
  },
  {
    id: 'E. Europe Standard Time',
    displayName: '(UTC+02:00) Chisinau',
    offset: '+02:00',
    regionTimeZone: {
      '001': 'Europe/Chisinau',
      MD: 'Europe/Chisinau',
    },
  },
  {
    id: 'Syria Standard Time',
    displayName: '(UTC+02:00) Damascus',
    offset: '+02:00',
    regionTimeZone: {
      '001': 'Asia/Damascus',
      SY: 'Asia/Damascus',
    },
  },
  {
    id: 'West Bank Standard Time',
    displayName: '(UTC+02:00) Gaza, Hebron',
    offset: '+02:00',
    regionTimeZone: {
      '001': 'Asia/Hebron',
      PS: 'Asia/Hebron Asia/Gaza',
    },
  },
  {
    id: 'South Africa Standard Time',
    displayName: '(UTC+02:00) Harare, Pretoria',
    offset: '+02:00',
    regionTimeZone: {
      '001': 'Africa/Johannesburg',
      BI: 'Africa/Bujumbura',
      BW: 'Africa/Gaborone',
      CD: 'Africa/Lubumbashi',
      LS: 'Africa/Maseru',
      MW: 'Africa/Blantyre',
      MZ: 'Africa/Maputo',
      RW: 'Africa/Kigali',
      SZ: 'Africa/Mbabane',
      ZA: 'Africa/Johannesburg',
      ZM: 'Africa/Lusaka',
      ZW: 'Africa/Harare',
      ZZ: 'Etc/GMT-2',
    },
  },
  {
    id: 'FLE Standard Time',
    displayName: '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
    offset: '+02:00',
    regionTimeZone: {
      '001': 'Europe/Kiev',
      AX: 'Europe/Mariehamn',
      BG: 'Europe/Sofia',
      EE: 'Europe/Tallinn',
      FI: 'Europe/Helsinki',
      LT: 'Europe/Vilnius',
      LV: 'Europe/Riga',
      UA: 'Europe/Kiev Europe/Uzhgorod Europe/Zaporozhye',
    },
  },
  {
    id: 'Israel Standard Time',
    displayName: '(UTC+02:00) Jerusalem',
    offset: '+02:00',
    regionTimeZone: {
      '001': 'Asia/Jerusalem',
      IL: 'Asia/Jerusalem',
    },
  },
  {
    id: 'South Sudan Standard Time',
    displayName: '(UTC+02:00) Juba',
    offset: '+02:00',
  },
  {
    id: 'Kaliningrad Standard Time',
    displayName: '(UTC+02:00) Kaliningrad',
    offset: '+02:00',
    regionTimeZone: {
      '001': 'Europe/Kaliningrad',
      RU: 'Europe/Kaliningrad',
    },
  },
  {
    id: 'Sudan Standard Time',
    displayName: '(UTC+02:00) Khartoum',
    offset: '+02:00',
    regionTimeZone: {
      '001': 'Africa/Khartoum',
      SD: 'Africa/Khartoum',
    },
  },
  {
    id: 'Libya Standard Time',
    displayName: '(UTC+02:00) Tripoli',
    offset: '+02:00',
    regionTimeZone: {
      '001': 'Africa/Tripoli',
      LY: 'Africa/Tripoli',
    },
  },
  {
    id: 'Namibia Standard Time',
    displayName: '(UTC+02:00) Windhoek',
    offset: '+02:00',
    regionTimeZone: {
      '001': 'Africa/Windhoek',
      NA: 'Africa/Windhoek',
    },
  },
  {
    id: 'Jordan Standard Time',
    displayName: '(UTC+03:00) Amman',
    offset: '+03:00',
    regionTimeZone: {
      '001': 'Asia/Amman',
      JO: 'Asia/Amman',
    },
  },
  {
    id: 'Arabic Standard Time',
    displayName: '(UTC+03:00) Baghdad',
    offset: '+03:00',
    regionTimeZone: {
      '001': 'Asia/Baghdad',
      IQ: 'Asia/Baghdad',
    },
  },
  {
    id: 'Turkey Standard Time',
    displayName: '(UTC+03:00) Istanbul',
    offset: '+03:00',
    regionTimeZone: {
      '001': 'Europe/Istanbul',
      TR: 'Europe/Istanbul',
    },
  },
  {
    id: 'Arab Standard Time',
    displayName: '(UTC+03:00) Kuwait, Riyadh',
    offset: '+03:00',
    regionTimeZone: {
      '001': 'Asia/Riyadh',
      BH: 'Asia/Bahrain',
      KW: 'Asia/Kuwait',
      QA: 'Asia/Qatar',
      SA: 'Asia/Riyadh',
      YE: 'Asia/Aden',
    },
  },
  {
    id: 'Belarus Standard Time',
    displayName: '(UTC+03:00) Minsk',
    offset: '+03:00',
    regionTimeZone: {
      '001': 'Europe/Minsk',
      BY: 'Europe/Minsk',
    },
  },
  {
    id: 'Russian Standard Time',
    displayName: '(UTC+03:00) Moscow, St. Petersburg',
    offset: '+03:00',
    regionTimeZone: {
      '001': 'Europe/Moscow',
      RU: 'Europe/Moscow Europe/Kirov Europe/Volgograd',
      UA: 'Europe/Simferopol',
    },
  },
  {
    id: 'E. Africa Standard Time',
    displayName: '(UTC+03:00) Nairobi',
    offset: '+03:00',
    regionTimeZone: {
      '001': 'Africa/Nairobi',
      AQ: 'Antarctica/Syowa',
      DJ: 'Africa/Djibouti',
      ER: 'Africa/Asmera',
      ET: 'Africa/Addis_Ababa',
      KE: 'Africa/Nairobi',
      KM: 'Indian/Comoro',
      MG: 'Indian/Antananarivo',
      SO: 'Africa/Mogadishu',
      SS: 'Africa/Juba',
      TZ: 'Africa/Dar_es_Salaam',
      UG: 'Africa/Kampala',
      YT: 'Indian/Mayotte',
      ZZ: 'Etc/GMT-3',
    },
  },
  {
    id: 'Volgograd Standard Time',
    displayName: '(UTC+03:00) Volgograd',
    offset: '+03:00',
  },
  {
    id: 'Iran Standard Time',
    displayName: '(UTC+03:30) Tehran',
    offset: '+03:30',
    regionTimeZone: {
      '001': 'Asia/Tehran',
      IR: 'Asia/Tehran',
    },
  },
  {
    id: 'Arabian Standard Time',
    displayName: '(UTC+04:00) Abu Dhabi, Muscat',
    offset: '+04:00',
    regionTimeZone: {
      '001': 'Asia/Dubai',
      AE: 'Asia/Dubai',
      OM: 'Asia/Muscat',
      ZZ: 'Etc/GMT-4',
    },
  },
  {
    id: 'Astrakhan Standard Time',
    displayName: '(UTC+04:00) Astrakhan, Ulyanovsk',
    offset: '+04:00',
    regionTimeZone: {
      '001': 'Europe/Astrakhan',
      RU: 'Europe/Astrakhan Europe/Ulyanovsk',
    },
  },
  {
    id: 'Azerbaijan Standard Time',
    displayName: '(UTC+04:00) Baku',
    offset: '+04:00',
    regionTimeZone: {
      '001': 'Asia/Baku',
      AZ: 'Asia/Baku',
    },
  },
  {
    id: 'Russia Time Zone 3',
    displayName: '(UTC+04:00) Izhevsk, Samara',
    offset: '+04:00',
    regionTimeZone: {
      '001': 'Europe/Samara',
      RU: 'Europe/Samara',
    },
  },
  {
    id: 'Mauritius Standard Time',
    displayName: '(UTC+04:00) Port Louis',
    offset: '+04:00',
    regionTimeZone: {
      '001': 'Indian/Mauritius',
      MU: 'Indian/Mauritius',
      RE: 'Indian/Reunion',
      SC: 'Indian/Mahe',
    },
  },
  {
    id: 'Saratov Standard Time',
    displayName: '(UTC+04:00) Saratov',
    offset: '+04:00',
    regionTimeZone: {
      '001': 'Europe/Saratov',
      RU: 'Europe/Saratov',
    },
  },
  {
    id: 'Georgian Standard Time',
    displayName: '(UTC+04:00) Tbilisi',
    offset: '+04:00',
    regionTimeZone: {
      '001': 'Asia/Tbilisi',
      GE: 'Asia/Tbilisi',
    },
  },
  {
    id: 'Caucasus Standard Time',
    displayName: '(UTC+04:00) Yerevan',
    offset: '+04:00',
    regionTimeZone: {
      '001': 'Asia/Yerevan',
      AM: 'Asia/Yerevan',
    },
  },
  {
    id: 'Afghanistan Standard Time',
    displayName: '(UTC+04:30) Kabul',
    offset: '+04:30',
    regionTimeZone: {
      '001': 'Asia/Kabul',
      AF: 'Asia/Kabul',
    },
  },
  {
    id: 'West Asia Standard Time',
    displayName: '(UTC+05:00) Ashgabat, Tashkent',
    offset: '+05:00',
    regionTimeZone: {
      '001': 'Asia/Tashkent',
      AQ: 'Antarctica/Mawson',
      KZ: 'Asia/Oral Asia/Aqtau Asia/Aqtobe Asia/Atyrau Asia/Qyzylorda',
      MV: 'Indian/Maldives',
      TF: 'Indian/Kerguelen',
      TJ: 'Asia/Dushanbe',
      TM: 'Asia/Ashgabat',
      UZ: 'Asia/Tashkent Asia/Samarkand',
      ZZ: 'Etc/GMT-5',
    },
  },
  {
    id: 'Ekaterinburg Standard Time',
    displayName: '(UTC+05:00) Ekaterinburg',
    offset: '+05:00',
    regionTimeZone: {
      '001': 'Asia/Yekaterinburg',
      RU: 'Asia/Yekaterinburg',
    },
  },
  {
    id: 'Pakistan Standard Time',
    displayName: '(UTC+05:00) Islamabad, Karachi',
    offset: '+05:00',
    regionTimeZone: {
      '001': 'Asia/Karachi',
      PK: 'Asia/Karachi',
    },
  },
  {
    id: 'Qyzylorda Standard Time',
    displayName: '(UTC+05:00) Qyzylorda',
    offset: '+05:00',
  },
  {
    id: 'India Standard Time',
    displayName: '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
    offset: '+05:30',
    regionTimeZone: {
      '001': 'Asia/Calcutta',
      IN: 'Asia/Calcutta',
    },
  },
  {
    id: 'Sri Lanka Standard Time',
    displayName: '(UTC+05:30) Sri Jayawardenepura',
    offset: '+05:30',
    regionTimeZone: {
      '001': 'Asia/Colombo',
      LK: 'Asia/Colombo',
    },
  },
  {
    id: 'Nepal Standard Time',
    displayName: '(UTC+05:45) Kathmandu',
    offset: '+05:45',
    regionTimeZone: {
      '001': 'Asia/Katmandu',
      NP: 'Asia/Katmandu',
    },
  },
  {
    id: 'Central Asia Standard Time',
    displayName: '(UTC+06:00) Astana',
    offset: '+06:00',
    regionTimeZone: {
      '001': 'Asia/Almaty',
      AQ: 'Antarctica/Vostok',
      CN: 'Asia/Urumqi',
      IO: 'Indian/Chagos',
      KG: 'Asia/Bishkek',
      KZ: 'Asia/Almaty Asia/Qostanay',
      ZZ: 'Etc/GMT-6',
    },
  },
  {
    id: 'Bangladesh Standard Time',
    displayName: '(UTC+06:00) Dhaka',
    offset: '+06:00',
    regionTimeZone: {
      '001': 'Asia/Dhaka',
      BD: 'Asia/Dhaka',
      BT: 'Asia/Thimphu',
    },
  },
  {
    id: 'Omsk Standard Time',
    displayName: '(UTC+06:00) Omsk',
    offset: '+06:00',
    regionTimeZone: {
      '001': 'Asia/Omsk',
      RU: 'Asia/Omsk',
    },
  },
  {
    id: 'Myanmar Standard Time',
    displayName: '(UTC+06:30) Yangon (Rangoon)',
    offset: '+06:30',
    regionTimeZone: {
      '001': 'Asia/Rangoon',
      CC: 'Indian/Cocos',
      MM: 'Asia/Rangoon',
    },
  },
  {
    id: 'SE Asia Standard Time',
    displayName: '(UTC+07:00) Bangkok, Hanoi, Jakarta',
    offset: '+07:00',
    regionTimeZone: {
      '001': 'Asia/Bangkok',
      AQ: 'Antarctica/Davis',
      CX: 'Indian/Christmas',
      ID: 'Asia/Jakarta Asia/Pontianak',
      KH: 'Asia/Phnom_Penh',
      LA: 'Asia/Vientiane',
      TH: 'Asia/Bangkok',
      VN: 'Asia/Saigon',
      ZZ: 'Etc/GMT-7',
    },
  },
  {
    id: 'Altai Standard Time',
    displayName: '(UTC+07:00) Barnaul, Gorno-Altaysk',
    offset: '+07:00',
    regionTimeZone: {
      '001': 'Asia/Barnaul',
      RU: 'Asia/Barnaul',
    },
  },
  {
    id: 'W. Mongolia Standard Time',
    displayName: '(UTC+07:00) Hovd',
    offset: '+07:00',
    regionTimeZone: {
      '001': 'Asia/Hovd',
      MN: 'Asia/Hovd',
    },
  },
  {
    id: 'North Asia Standard Time',
    displayName: '(UTC+07:00) Krasnoyarsk',
    offset: '+07:00',
    regionTimeZone: {
      '001': 'Asia/Krasnoyarsk',
      RU: 'Asia/Krasnoyarsk Asia/Novokuznetsk',
    },
  },
  {
    id: 'N. Central Asia Standard Time',
    displayName: '(UTC+07:00) Novosibirsk',
    offset: '+07:00',
    regionTimeZone: {
      '001': 'Asia/Novosibirsk',
      RU: 'Asia/Novosibirsk',
    },
  },
  {
    id: 'Tomsk Standard Time',
    displayName: '(UTC+07:00) Tomsk',
    offset: '+07:00',
    regionTimeZone: {
      '001': 'Asia/Tomsk',
      RU: 'Asia/Tomsk',
    },
  },
  {
    id: 'China Standard Time',
    displayName: '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
    offset: '+08:00',
    regionTimeZone: {
      '001': 'Asia/Shanghai',
      CN: 'Asia/Shanghai',
      HK: 'Asia/Hong_Kong',
      MO: 'Asia/Macau',
    },
  },
  {
    id: 'North Asia East Standard Time',
    displayName: '(UTC+08:00) Irkutsk',
    offset: '+08:00',
    regionTimeZone: {
      '001': 'Asia/Irkutsk',
      RU: 'Asia/Irkutsk',
    },
  },
  {
    id: 'Singapore Standard Time',
    displayName: '(UTC+08:00) Kuala Lumpur, Singapore',
    offset: '+08:00',
    regionTimeZone: {
      '001': 'Asia/Singapore',
      BN: 'Asia/Brunei',
      ID: 'Asia/Makassar',
      MY: 'Asia/Kuala_Lumpur Asia/Kuching',
      PH: 'Asia/Manila',
      SG: 'Asia/Singapore',
      ZZ: 'Etc/GMT-8',
    },
  },
  {
    id: 'W. Australia Standard Time',
    displayName: '(UTC+08:00) Perth',
    offset: '+08:00',
    regionTimeZone: {
      '001': 'Australia/Perth',
      AQ: 'Antarctica/Casey',
      AU: 'Australia/Perth',
    },
  },
  {
    id: 'Taipei Standard Time',
    displayName: '(UTC+08:00) Taipei',
    offset: '+08:00',
    regionTimeZone: {
      '001': 'Asia/Taipei',
      TW: 'Asia/Taipei',
    },
  },
  {
    id: 'Ulaanbaatar Standard Time',
    displayName: '(UTC+08:00) Ulaanbaatar',
    offset: '+08:00',
    regionTimeZone: {
      '001': 'Asia/Ulaanbaatar',
      MN: 'Asia/Ulaanbaatar Asia/Choibalsan',
    },
  },
  {
    id: 'Aus Central W. Standard Time',
    displayName: '(UTC+08:45) Eucla',
    offset: '+08:45',
    regionTimeZone: {
      '001': 'Australia/Eucla',
      AU: 'Australia/Eucla',
    },
  },
  {
    id: 'Transbaikal Standard Time',
    displayName: '(UTC+09:00) Chita',
    offset: '+09:00',
    regionTimeZone: {
      '001': 'Asia/Chita',
      RU: 'Asia/Chita',
    },
  },
  {
    id: 'Tokyo Standard Time',
    displayName: '(UTC+09:00) Osaka, Sapporo, Tokyo',
    offset: '+09:00',
    regionTimeZone: {
      '001': 'Asia/Tokyo',
      ID: 'Asia/Jayapura',
      JP: 'Asia/Tokyo',
      PW: 'Pacific/Palau',
      TL: 'Asia/Dili',
      ZZ: 'Etc/GMT-9',
    },
  },
  {
    id: 'North Korea Standard Time',
    displayName: '(UTC+09:00) Pyongyang',
    offset: '+09:00',
    regionTimeZone: {
      '001': 'Asia/Pyongyang',
      KP: 'Asia/Pyongyang',
    },
  },
  {
    id: 'Korea Standard Time',
    displayName: '(UTC+09:00) Seoul',
    offset: '+09:00',
    regionTimeZone: {
      '001': 'Asia/Seoul',
      KR: 'Asia/Seoul',
    },
  },
  {
    id: 'Yakutsk Standard Time',
    displayName: '(UTC+09:00) Yakutsk',
    offset: '+09:00',
    regionTimeZone: {
      '001': 'Asia/Yakutsk',
      RU: 'Asia/Yakutsk Asia/Khandyga',
    },
  },
  {
    id: 'Cen. Australia Standard Time',
    displayName: '(UTC+09:30) Adelaide',
    offset: '+09:30',
    regionTimeZone: {
      '001': 'Australia/Adelaide',
      AU: 'Australia/Adelaide Australia/Broken_Hill',
    },
  },
  {
    id: 'AUS Central Standard Time',
    displayName: '(UTC+09:30) Darwin',
    offset: '+09:30',
    regionTimeZone: {
      '001': 'Australia/Darwin',
      AU: 'Australia/Darwin',
    },
  },
  {
    id: 'E. Australia Standard Time',
    displayName: '(UTC+10:00) Brisbane',
    offset: '+10:00',
    regionTimeZone: {
      '001': 'Australia/Brisbane',
      AU: 'Australia/Brisbane Australia/Lindeman',
    },
  },
  {
    id: 'AUS Eastern Standard Time',
    displayName: '(UTC+10:00) Canberra, Melbourne, Sydney',
    offset: '+10:00',
    regionTimeZone: {
      '001': 'Australia/Sydney',
      AU: 'Australia/Sydney Australia/Melbourne',
    },
  },
  {
    id: 'West Pacific Standard Time',
    displayName: '(UTC+10:00) Guam, Port Moresby',
    offset: '+10:00',
    regionTimeZone: {
      '001': 'Pacific/Port_Moresby',
      AQ: 'Antarctica/DumontDUrville',
      FM: 'Pacific/Truk',
      GU: 'Pacific/Guam',
      MP: 'Pacific/Saipan',
      PG: 'Pacific/Port_Moresby',
      ZZ: 'Etc/GMT-10',
    },
  },
  {
    id: 'Tasmania Standard Time',
    displayName: '(UTC+10:00) Hobart',
    offset: '+10:00',
    regionTimeZone: {
      '001': 'Australia/Hobart',
      AU: 'Australia/Hobart Australia/Currie',
    },
  },
  {
    id: 'Vladivostok Standard Time',
    displayName: '(UTC+10:00) Vladivostok',
    offset: '+10:00',
    regionTimeZone: {
      '001': 'Asia/Vladivostok',
      RU: 'Asia/Vladivostok Asia/Ust-Nera',
    },
  },
  {
    id: 'Lord Howe Standard Time',
    displayName: '(UTC+10:30) Lord Howe Island',
    offset: '+10:30',
    regionTimeZone: {
      '001': 'Australia/Lord_Howe',
      AU: 'Australia/Lord_Howe',
    },
  },
  {
    id: 'Bougainville Standard Time',
    displayName: '(UTC+11:00) Bougainville Island',
    offset: '+11:00',
    regionTimeZone: {
      '001': 'Pacific/Bougainville',
      PG: 'Pacific/Bougainville',
    },
  },
  {
    id: 'Russia Time Zone 10',
    displayName: '(UTC+11:00) Chokurdakh',
    offset: '+11:00',
    regionTimeZone: {
      '001': 'Asia/Srednekolymsk',
      RU: 'Asia/Srednekolymsk',
    },
  },
  {
    id: 'Magadan Standard Time',
    displayName: '(UTC+11:00) Magadan',
    offset: '+11:00',
    regionTimeZone: {
      '001': 'Asia/Magadan',
      RU: 'Asia/Magadan',
    },
  },
  {
    id: 'Norfolk Standard Time',
    displayName: '(UTC+11:00) Norfolk Island',
    offset: '+11:00',
    regionTimeZone: {
      '001': 'Pacific/Norfolk',
      NF: 'Pacific/Norfolk',
    },
  },
  {
    id: 'Sakhalin Standard Time',
    displayName: '(UTC+11:00) Sakhalin',
    offset: '+11:00',
    regionTimeZone: {
      '001': 'Asia/Sakhalin',
      RU: 'Asia/Sakhalin',
    },
  },
  {
    id: 'Central Pacific Standard Time',
    displayName: '(UTC+11:00) Solomon Is., New Caledonia',
    offset: '+11:00',
    regionTimeZone: {
      '001': 'Pacific/Guadalcanal',
      AU: 'Antarctica/Macquarie',
      FM: 'Pacific/Ponape Pacific/Kosrae',
      NC: 'Pacific/Noumea',
      SB: 'Pacific/Guadalcanal',
      VU: 'Pacific/Efate',
      ZZ: 'Etc/GMT-11',
    },
  },
  {
    id: 'Russia Time Zone 11',
    displayName: '(UTC+12:00) Anadyr, Petropavlovsk-Kamchatsky',
    offset: '+12:00',
    regionTimeZone: {
      '001': 'Asia/Kamchatka',
      RU: 'Asia/Kamchatka Asia/Anadyr',
    },
  },
  {
    id: 'New Zealand Standard Time',
    displayName: '(UTC+12:00) Auckland, Wellington',
    offset: '+12:00',
    regionTimeZone: {
      '001': 'Pacific/Auckland',
      AQ: 'Antarctica/McMurdo',
      NZ: 'Pacific/Auckland',
    },
  },
  {
    id: 'UTC+12',
    displayName: '(UTC+12:00) Coordinated Universal Time+12',
    offset: '+12:00',
    regionTimeZone: {
      '001': 'Etc/GMT-12',
      KI: 'Pacific/Tarawa',
      MH: 'Pacific/Majuro Pacific/Kwajalein',
      NR: 'Pacific/Nauru',
      TV: 'Pacific/Funafuti',
      UM: 'Pacific/Wake',
      WF: 'Pacific/Wallis',
      ZZ: 'Etc/GMT-12',
    },
  },
  {
    id: 'Fiji Standard Time',
    displayName: '(UTC+12:00) Fiji',
    offset: '+12:00',
    regionTimeZone: {
      '001': 'Pacific/Fiji',
      FJ: 'Pacific/Fiji',
    },
  },
  {
    id: 'Kamchatka Standard Time',
    displayName: '(UTC+12:00) Petropavlovsk-Kamchatsky - Old',
    offset: '+12:00',
  },
  {
    id: 'Chatham Islands Standard Time',
    displayName: '(UTC+12:45) Chatham Islands',
    offset: '+12:45',
    regionTimeZone: {
      '001': 'Pacific/Chatham',
      NZ: 'Pacific/Chatham',
    },
  },
  {
    id: 'UTC+13',
    displayName: '(UTC+13:00) Coordinated Universal Time+13',
    offset: '+13:00',
    regionTimeZone: {
      '001': 'Etc/GMT-13',
      KI: 'Pacific/Enderbury',
      TK: 'Pacific/Fakaofo',
      ZZ: 'Etc/GMT-13',
    },
  },
  {
    id: 'Tonga Standard Time',
    displayName: "(UTC+13:00) Nuku'alofa",
    offset: '+13:00',
    regionTimeZone: {
      '001': 'Pacific/Tongatapu',
      TO: 'Pacific/Tongatapu',
    },
  },
  {
    id: 'Samoa Standard Time',
    displayName: '(UTC+13:00) Samoa',
    offset: '+13:00',
    regionTimeZone: {
      '001': 'Pacific/Apia',
      WS: 'Pacific/Apia',
    },
  },
  {
    id: 'Line Islands Standard Time',
    displayName: '(UTC+14:00) Kiritimati Island',
    offset: '+14:00',
    regionTimeZone: {
      '001': 'Pacific/Kiritimati',
      KI: 'Pacific/Kiritimati',
      ZZ: 'Etc/GMT-14',
    },
  },
]

export const handlers = [
  rest.get('/:region/api/timezones', (_req, res, ctx) =>
    res(ctx.delay(0), ctx.json(timeZones))
  ),
  rest.get('/api/timezones', (_req, res, ctx) =>
    res(ctx.delay(0), ctx.json(timeZones))
  ),
]

// https://command-uat.willowinc.com/au/api/timezones
