// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Willow.CommandAndControl.Data;

#nullable disable

namespace Willow.CommandAndControl.WebApi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Willow.CommandAndControl.Data.Models.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExtraInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequestedCommandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResolvedCommandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("UpdatedBy", "Willow.CommandAndControl.Data.Models.ActivityLog.UpdatedBy#User", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("RequestedCommandId");

                    b.HasIndex("ResolvedCommandId");

                    b.ToTable("ActivityLog", (string)null);
                });

            modelBuilder.Entity("Willow.CommandAndControl.Data.Models.RequestedCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IsCapabilityOf")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsHostedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ReceivedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TwinId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.ComplexProperty<Dictionary<string, object>>("StatusUpdatedBy", "Willow.CommandAndControl.Data.Models.RequestedCommand.StatusUpdatedBy#User", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TwinId");

                    b.HasIndex("TwinId", "IsCapabilityOf", "IsHostedBy", "Location", "ConnectorId", "ExternalId", "Unit");

                    b.ToTable("RequestedCommand", (string)null);
                });

            modelBuilder.Entity("Willow.CommandAndControl.Data.Models.ResolvedCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RequestedCommandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("StatusUpdatedBy", "Willow.CommandAndControl.Data.Models.ResolvedCommand.StatusUpdatedBy#User", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("RequestedCommandId");

                    b.ToTable("ResolvedCommand", (string)null);
                });

            modelBuilder.Entity("Willow.CommandAndControl.Data.Models.ActivityLog", b =>
                {
                    b.HasOne("Willow.CommandAndControl.Data.Models.RequestedCommand", "RequestedCommand")
                        .WithMany()
                        .HasForeignKey("RequestedCommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Willow.CommandAndControl.Data.Models.ResolvedCommand", "ResolvedCommand")
                        .WithMany()
                        .HasForeignKey("ResolvedCommandId");

                    b.Navigation("RequestedCommand");

                    b.Navigation("ResolvedCommand");
                });

            modelBuilder.Entity("Willow.CommandAndControl.Data.Models.RequestedCommand", b =>
                {
                    b.OwnsMany("Willow.CommandAndControl.Application.Models.LocationTwin", "Locations", b1 =>
                        {
                            b1.Property<Guid>("RequestedCommandId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("LocationModelName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasAnnotation("Relational:JsonPropertyName", "LocationModelId");

                            b1.Property<string>("LocationTwinName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasAnnotation("Relational:JsonPropertyName", "LocationTwinId");

                            b1.Property<int>("Order")
                                .HasColumnType("int");

                            b1.Property<string>("TwinName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasAnnotation("Relational:JsonPropertyName", "TwinId");

                            b1.HasKey("RequestedCommandId", "Id");

                            b1.ToTable("RequestedCommand");

                            b1.ToJson("Locations");

                            b1.WithOwner()
                                .HasForeignKey("RequestedCommandId");
                        });

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Willow.CommandAndControl.Data.Models.ResolvedCommand", b =>
                {
                    b.HasOne("Willow.CommandAndControl.Data.Models.RequestedCommand", "RequestedCommand")
                        .WithMany("ResolvedCommands")
                        .HasForeignKey("RequestedCommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedCommand");
                });

            modelBuilder.Entity("Willow.CommandAndControl.Data.Models.RequestedCommand", b =>
                {
                    b.Navigation("ResolvedCommands");
                });
#pragma warning restore 612, 618
        }
    }
}
