trigger:
  branches:
    include:
      - main
      - releases/real-estate/*
  paths:
    include:
      - extensions/real-estate/back-end/PlatformPortalXL/*

pr:
  branches:
    include:
      - main
      - releases/real-estate/*
  paths:
    include:
      - extensions/real-estate/back-end/PlatformPortalXL/*

variables:
  - name: buildConfiguration
    value: Release
  - name: majorVersion # This is used to determine keyvault prefix within PrefixKeyVaultSecretManager
    value: 1
  - name: projectPath
    value: extensions/real-estate/back-end/PlatformPortalXL
  - name: srcRoot
    value: $(Build.SourcesDirectory)/$(projectPath)
  - name: srcProjectDir
    value: $(projectPath)/src/PlatformPortalXL
  - name: testProjectDir
    value: $(projectPath)/test/PlatformPortalXL.Test
  - group: EphemeralEnvironments

resources:
  repositories:
    - repository: infrastructure
      type: github
      name: Willowinc/AzurePlatform
      endpoint: github.com_willow-github-svc-Twin Platform

stages:
- stage: Build
  jobs:
  - job: BuildArtifactsJob
    pool:
      vmImage: 'Ubuntu-latest'

    steps:
    - template: ../../../../libraries/scripts/semantic-build-numbers-template.yml
      parameters:
        majorVersion: $(majorVersion)
        
    - template: ../../../../libraries/scripts/dotnet-build-test-publish-net7.yml
      parameters:
        srcProjectDir: $(srcProjectDir)
        testProjectDir: $(testProjectDir)
        zipAfterPublish: true
        restoreGithubNugetPackages: true

    - template: ../../../../libraries/scripts/docker-push-template.yml
      parameters:
        imageName: portalxl
        productName: willowplatform
        dockerfile: $(srcRoot)/src/PlatformPortalXL/Dockerfile.zipped
        dockerContext: $(Build.ArtifactStagingDirectory)/
        branchTags: true
        alwaysPush: true

    - task: PublishBuildArtifacts@1

- template: EphemeralEnvironments/ephemeral-pr.yaml@infrastructure
  parameters:
    dependsOn: Build
    resourceServiceConnection: 'az-platform-dev-Twin Platform'
    acrSubscriptionServiceConnection: 'az-k8s-internal-Twin Platform'
    templateRepository: infrastructure
