trigger:
  branches:
    include:
      - main
      - releases/real-estate/*
  paths:
    include:
      - extensions/real-estate/back-end/DigitalTwinCore/*

pr:
  branches:
    include:
      - main
      - releases/real-estate/*
  paths:
    include:
      - extensions/real-estate/back-end/DigitalTwinCore/*

parameters:
- name: acr_push_prd
  displayName: Push to ACR (PRD)
  type: boolean
  default: false
- name: acr_push_dev
  displayName: Push to ACR (DEV)
  type: boolean
  default: false

variables:
  - name: buildConfiguration
    value: Release
  - name: majorVersion # This is used to determine keyvault prefix within PrefixKeyVaultSecretManager
    value: 1
  - name: projectPath
    value: extensions/real-estate/back-end/DigitalTwinCore
  - name: srcRoot
    value: $(Build.SourcesDirectory)/$(projectPath)
  - name: srcProjectDir
    value: $(projectPath)/src/DigitalTwinCore
  - name: testProjectDir
    value: $(projectPath)/test/DigitalTwinCore.Test
  - group: EphemeralEnvironments

resources:
  repositories:
    - repository: infrastructure
      type: github
      name: Willowinc/AzurePlatform
      endpoint: github.com_willow-github-svc-Twin Platform

stages:
- stage: Build
  jobs:
  - job: BuildArtifactsJob
    pool:
      vmImage: 'Ubuntu-latest'

    steps:
    - template: ../../../../libraries/scripts/semantic-build-numbers-template.yml
      parameters:
        majorVersion: $(majorVersion)

    - template: ../../../../libraries/scripts/dotnet-build-test-publish-net7.yml
      parameters:
        srcProjectDir: $(srcProjectDir)
        testProjectDir: $(testProjectDir)
        zipAfterPublish: false
        restoreGithubNugetPackages: true

    - template: ../../../../libraries/scripts/docker-push-template.yml
      parameters:
        imageName: DigitalTwinCore
        productName: willowplatform
        dockerfile: $(srcRoot)/src/DigitalTwinCore/Dockerfile
        dockerContext: $(Build.ArtifactStagingDirectory)/DigitalTwinCore
        branchTags: true
        alwaysPush: true

    - ${{if parameters.acr_push_dev }}:
      - template: ../../../../libraries/scripts/docker-push-template.yml
        parameters:
          imageName: DigitalTwinCore
          productName: willowplatform
          dockerfile: $(srcRoot)/src/DigitalTwinCore/Dockerfile
          dockerContext: $(Build.ArtifactStagingDirectory)/DigitalTwinCore
          branchTags: true
          alwaysPush: true
          containerRegistry: acr-crwildevshared01-Twin Platform

    - ${{if parameters.acr_push_prd }}:
      - template: ../../../../libraries/scripts/docker-push-template.yml
        parameters:
          imageName: DigitalTwinCore
          productName: willowplatform
          dockerfile: $(srcRoot)/src/DigitalTwinCore/Dockerfile
          dockerContext: $(Build.ArtifactStagingDirectory)/DigitalTwinCore
          branchTags: true
          alwaysPush: true
          containerRegistry: acr-crwilprdshared01-Twin Platform
          
    - script: |
        cd $(Build.ArtifactStagingDirectory)
        cd DigitalTwinCore
        zip -r DigitalTwinCore.zip .
        mv DigitalTwinCore.zip ..
        cd ..
        rm -rf DigitalTwinCore
      displayName: 'Zip and Delete Files'

    - task: PublishBuildArtifacts@1

- template: EphemeralEnvironments/ephemeral-pr.yaml@infrastructure
  parameters:
    dependsOn: Build
    resourceServiceConnection: 'az-platform-dev-Twin Platform'
    acrSubscriptionServiceConnection: 'az-k8s-internal-Twin Platform'
    templateRepository: infrastructure
