name: DotNet Sonar Analyze
description: Analyze and publish results to SonarQube
inputs:
  sonar_token:
    required: true
    description: 'Sonarqube access token'
  working_directory:
    description: 'Working directory'
    default: ''
runs:
  using: composite
  steps:
  - name: Sonar Analyze
    shell: pwsh
    run: dotnet sonarscanner end /d:sonar.login="${{ inputs.sonar_token }}"
    working-directory: ${{ inputs.working_directory == '' && github.workspace || inputs.working_directory }}