name: DotNet Sonar Prepare
description: Install and start SonarQube analyzer
inputs:
  sonar_project_name:
    description: 'Sonarqube project name'
    required: true
  sonar_host_url:
    description: 'Sonarqube host instance'
    required: true
    default: 'https://sq.willowinc.com/'
  sonar_token:
    description: 'Sonarqube access token'
    required: false
  coverage_file_name:
    description: 'Coverage file name'
    required: false
    default: 'coverage.opencover.xml'
  working_directory:
    description: 'Working directory'
    default: ''
runs:
  using: composite
  steps:
  - name: Set up JDK 11
    uses: actions/setup-java@v3
    with:
      distribution: 'microsoft'
      java-version: '11'
      
  - name: Sonar Prepare
    shell: pwsh
    run: |-
      dotnet tool install --global dotnet-sonarscanner
      dotnet sonarscanner begin /k:"${{ inputs.sonar_project_name }}" /d:sonar.login="${{ inputs.sonar_token }}" /d:sonar.dotnet.excludeTestProjects=true /d:sonar.host.url="${{ inputs.sonar_host_url }}" /d:sonar.cs.opencover.reportsPath="**/${{ inputs.coverage_file_name }}"
    working-directory: ${{ inputs.working_directory == '' && github.workspace || inputs.working_directory }}