IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
              WHERE TABLE_NAME = N'Notifications' AND COLUMN_NAME = N'SourceId')
BEGIN
    ALTER TABLE Notifications
    ADD SourceId NVARCHAR(250) NULL
END
