IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
              WHERE TABLE_NAME = N'ImpactScores' AND COLUMN_NAME = N'FieldId')
BEGIN
    ALTER TABLE ImpactScores ADD FieldId NVARCHAR(256) NULL;
END;

Go;
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
              WHERE TABLE_NAME = N'ImpactScores' AND COLUMN_NAME = N'FieldId')
BEGIN
    UPDATE ImpactScores SET FieldId=REPLACE(LOWER([Name]), ' ', '_');
END;
Go;
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
              WHERE TABLE_NAME = N'ImpactScores' AND COLUMN_NAME = N'FieldId')
BEGIN
    ALTER TABLE ImpactScores
    ALTER COLUMN FieldId NVARCHAR(256) NOT NULL;

END
