/* eslint-disable import/prefer-default-export */
export const testTwinVersions = {
  versions: [
    {
      user: { id: 'id1', firstName: 'John', lastName: 'Doe' },
      timestamp: new Date().toISOString(),
      twin: {
        etag: 'W/"f863ca23-9aff-4194-a776-cfdd628c617c"',
        name: 'new value',
        doNotUpdateThis: 'no update pls',
        emptyValue: '',
        siteID: '123',
        id: '123',
        uniqueID: 'read only',
        group: {
          hello: 'new nested value',
          booleanValue: true,
          subGroup: { sub: 'group', numberInSubgroup: 7 },
        },
        tags: { myTag: '123' },
        metadata: { modelId: 'myModelId' },
      },
    },
    {
      user: { id: 'id1', firstName: 'John', lastName: 'Doe' },
      timestamp: '2021-10-16T07:14:22.000Z',
      twin: {
        etag: 'W/"f863ca23-9aff-4194-a776-cfdd628c617c"',
        name: 'new value',
        updateThis: 'new value',
        doNotUpdateThis: 'no update pls',
        emptyValue: '',
        siteID: '123',
        id: '123',
        uniqueID: 'read only',
        group: {
          hello: 'new nested value',
          booleanValue: true,
          subGroup: { sub: 'group', numberInSubgroup: 7 },
        },
        tags: { myTag: '123' },
        metadata: { modelId: 'myModelId' },
      },
    },
    {
      user: { id: 'id1', firstName: 'John', lastName: 'Doe' },
      timestamp: '2021-10-15T22:00:00.000Z',
      twin: {
        etag: 'W/"f863ca23-9aff-4194-a776-cfdd628c617c"',
        name: 'Hello',
        updateThis: 'new value',
        doNotUpdateThis: 'no update pls',
        emptyValue: '',
        siteID: '123',
        id: '123',
        uniqueID: 'read only',
        group: {
          hello: 'new nested value',
          booleanValue: true,
          subGroup: { sub: 'group', numberInSubgroup: 7 },
        },
        tags: { myTag: '123' },
        metadata: { modelId: 'myModelId' },
      },
    },
    {
      user: { id: 'id1', firstName: 'John', lastName: 'Doe' },
      timestamp: '2021-10-13T17:00:00.000Z',
      twin: {
        etag: 'W/"f863ca23-9aff-4194-a776-cfdd628c617c"',
        name: 'Hello',
        updateThis: 'new value',
        doNotUpdateThis: 'no update pls',
        emptyValue: '',
        siteID: '123',
        id: '123',
        uniqueID: 'read only',
        group: {
          hello: 'string in group',
          booleanValue: true,
          subGroup: { sub: 'group', numberInSubgroup: 7 },
        },
        tags: { myTag: '123' },
        metadata: { modelId: 'myModelId' },
      },
    },
    {
      user: { id: 'id1', firstName: 'John', lastName: 'Doe' },
      timestamp: '2021-10-12T07:00:00.000Z',
      twin: {
        etag: 'W/"f863ca23-9aff-4194-a776-cfdd628c617c"',
        name: 'Hello',
        updateThis: 'update this',
        doNotUpdateThis: 'no update pls',
        emptyValue: '',
        siteID: '123',
        id: '123',
        uniqueID: 'read only',
        group: {
          hello: 'string in group',
          booleanValue: true,
          subGroup: { sub: 'group', numberInSubgroup: 7 },
        },
        tags: { myTag: '123' },
        metadata: { modelId: 'myModelId' },
      },
    },
  ],
}
