import { TFunction } from 'react-i18next'
import _ from 'lodash'

export default function getTicketStatusTranslatedName(
  t: TFunction,
  status: string
) {
  if (!status) return undefined

  const camelCasedStatus = _.camelCase(status)

  switch (camelCasedStatus) {
    case 'open':
      return t('headers.open')
    /**
     * team had decided to name 'Resolved' => 'Completed' in UI without changing the API or data structure.
     * reference: https://dev.azure.com/willowdev/Unified/_workitems/edit/80429
     */
    case 'resolved':
      return t('headers.completed')
    case 'closed':
      return t('headers.closed')
    default:
      // In case ticket status is generated by 3rd party, we should return the status as is
      return t(`plainText.${camelCasedStatus}`, {
        defaultValue: status,
      })
  }
}
