apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: directorycore
  title: DirectoryCore
  description: User authentication/management
  annotations:
    sonarqube.org/project-key: 'DirectoryCore'
    dev.azure.com/project-repo: WillowPlatform/DirectoryCore
  tags:
    - realestate
  links:
    - url: https://dev.azure.com/willowdev/WillowPlatform/_git/DirectoryCore
      title: Repo
      icon: web
    - url: https://dev.azure.com/willowdev/WillowPlatform/_build?definitionId=148
      title: Pipeline
      icon: web
    - url: https://saas.whitesourcesoftware.com/Wss/WSS.html#!project;id=6706638
      title: Whitesource
      icon: web
    - url: https://willow.atlassian.net/wiki/spaces/MAR/overview
      title: Wiki
      icon: web
    - url: https://portal.azure.com/#@willowinc.com/resource/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-plt-aue2-app-rsg/providers/Microsoft.Web/sites/wil-prd-plt-aue2-directorycore/appServices
      title: AU App Service
      icon: web
    - url: https://portal.azure.com/#@willowinc.com/resource/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-plt-weu2-app-rsg/providers/Microsoft.Web/sites/wil-prd-plt-weu2-directorycore/appServices
      title: EU App Service
      icon: web
    - url: https://portal.azure.com/#@willowinc.com/resource/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-plt-eu22-app-rsg/providers/Microsoft.Web/sites/wil-prd-plt-eu22-directorycore/appServices
      title: US App Service
      icon: web
spec:
  type: service
  lifecycle: production
  owner: pne_realestate
  system: realestate-system
  dependsOn: 
    [
      'resource:AU-RealEstate-keyvault',
      'resource:EU-RealEstate-keyvault',
      'resource:US-RealEstate-keyvault',
      'resource:AU-DirectoryCore-servicebus',
      'resource:EU-DirectoryCore-servicebus',
      'resource:US-DirectoryCore-servicebus',
      'resource:au-directorycore-db',
      'resource:us-directorycore-db',      
      'resource:eu-directorycore-db'
    ]
  providesApis:
    - DirectoryCore-Api
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: au-directorycore-db
  links:
    - url: https://portal.azure.com/#@willowinc.com/resource/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-plt-aue2-app-rsg/providers/Microsoft.Sql/servers/wil-prd-plt-aue2-sql/databases/DirectoryCoreDB/overview
      title: AU DirectoryCore DB
      icon: web
  description: AU DirectoryCore DB
spec:
  type: sqldb
  owner: pne_realestate
  system: realestate-system
  dependsOn: ['resource:au-realestate-sql-server']
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: us-directorycore-db
  links:
    - url: https://portal.azure.com/#@willowinc.com/resource/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-plt-eu22-app-rsg/providers/Microsoft.Sql/servers/wil-prd-plt-eu22-sql/databases/DirectoryCoreDB/overview
      title: US DirectoryCore DB
      icon: web
  description: US DirectoryCore DB
spec:
  type: sqldb
  owner: pne_realestate
  system: realestate-system
  dependsOn: ['resource:us-realestate-sql-server']
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: eu-directorycore-db
  links:
    - url: https://portal.azure.com/#@willowinc.com/resource/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-plt-weu2-app-rsg/providers/Microsoft.Sql/servers/wil-prd-plt-weu2-sql
      title: EU DirectoryCore DB
      icon: web
  description: EU DirectoryCore DB
spec:
  type: sqldb
  owner: pne_realestate
  system: realestate-system
  dependsOn: ['resource:eu-realestate-sql-server']
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: AU-DirectoryCore-servicebus
  links:
  - url: https://portal.azure.com/#@willowinc.com/resource/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-plt-aue2-app-rsg/providers/Microsoft.NotificationHubs/namespaces/wil-prd-plt-aue2-nhb-ns/NotificationHubs/wil-prd-plt-aue2-nhb/overview
    title: AU DirectoryCore ServiceBus
    icon: web
  description: ServiceBus
spec:
  type: ServiceBus
  owner: pne_realestate
  system: realestate-system
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: EU-DirectoryCore-servicebus
  links:
  - url: https://portal.azure.com/#@willowinc.com/resource/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-plt-weu2-app-rsg/providers/Microsoft.NotificationHubs/namespaces/wil-prd-plt-weu2-nhb-ns/notificationHubs/wil-prd-plt-weu2-nhb/overview
    title: EU DirectoryCore ServiceBus
    icon: web
  description: ServiceBus
spec:
  type: ServiceBus
  owner: pne_realestate
  system: realestate-system
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: US-DirectoryCore-servicebus
  links:
  - url: https://portal.azure.com/#@willowinc.com/resource/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-plt-eu22-app-rsg/providers/Microsoft.NotificationHubs/namespaces/wil-prd-plt-eu22-nhb-ns/notificationHubs/wil-prd-plt-eu22-nhb/overview
    title: US DirectoryCore ServiceBus
    icon: web
  description: ServiceBus
spec:
  type: ServiceBus
  owner: pne_realestate
  system: realestate-system
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: DirectoryCore-Api
  description: Directory Core Api
spec:
  type: openapi
  lifecycle: production
  owner: pne_realestate
  system: realestate-system
  definition:
    $text: https://wil-dev-plt-aue1-directorycore.azurewebsites.net/swagger/v1/swagger.json
  dependsOn: ['component:directorycore']
