export default [
  'DefaultBACnetConnector',
  'DefaultModbusConnector',
  'DefaultOpcDaConnector',
  'DefaultOpcUaConnector',
  'DefaultStreamAnalyticsConnector',
  'DefaultChipkinBACnetConnector',
  'DefaultSchneiderConnector',
  'DefaultVergeSenseConnector',
  'DefaultMachEnergyConnector',
  'DefaultMarketplaceConnector',
  'DefaultCCureConnector',
  'DefaultPointGrabConnector',
  'DefaultIntegritiConnector',
  'DefaultDeltaVConnector',
  'DefaultSiemensConnector',
]
