name: Create Release
description: Create GitHub release for PR or Main

inputs:
  files:
    description: Newline-delimited globs of paths to assets to upload for release
    required: false
  tag_name:
    description: Name of a tag.
    required: false
    default: ${{ github.ref }}
  name:
    description: Name of the release
    required: true
  pat:
    description: Personal Access Token. It should be used when the release needs to trigger another workflow.
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Release
      uses: softprops/action-gh-release@v1
      if: (github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/pull/')
      with:
        prerelease: ${{ startsWith(github.ref, 'refs/pull/') }}
        files: ${{ inputs.files }}
        tag_name: ${{ inputs.tag_name }}
        name: ${{ inputs.name }}
        generate_release_notes: true
        token: ${{ inputs.pat }}
