SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DT_Tags] (
	[Name] [nvarchar](128) NOT NULL,
	[TagType] [int] NOT NULL,
	CONSTRAINT [PK_DT_Tags] PRIMARY KEY CLUSTERED ([Name] ASC) 
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DT_TagTypes] (
	[Id] [int] NOT NULL,
	[Description] [nvarchar](256) NOT NULL
	CONSTRAINT [PK_DT_TagTypes] PRIMARY KEY CLUSTERED ([Id] ASC) 
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE dbo.DT_Tags ADD CONSTRAINT
	FK_DT_Tags_DT_TagTypes FOREIGN KEY
	(
	TagType
	) REFERENCES dbo.DT_TagTypes
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO

INSERT INTO [dbo].[DT_TagTypes]
	(Id, Description)
VALUES
	(0, 'General'),
	(1, '2D'),
	(2, '3D')
GO