BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO

ALTER TABLE dbo.DT_SiteSettings ADD
	SiteCodeForModelId nvarchar(32) NOT NULL CONSTRAINT DF_DT_SiteSettings_SiteCodeForModelId DEFAULT ('B121')
GO

ALTER TABLE dbo.DT_SiteSettings
	DROP CONSTRAINT DF_DT_SiteSettings_SiteCodeForModelId

ALTER TABLE dbo.DT_SiteSettings SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
