name: "Platform - Web - Test"

on:
  push:
    branches:
      - main
    paths:
      - extensions/real-estate/front-end/Web/**
  pull_request:
    branches:
      - main
    paths:
      - extensions/real-estate/front-end/Web/**
      - .github/workflows/platform_web_test.yml
  workflow_dispatch:
    inputs:
      push_dev_acr:
        type: boolean
        default: false
      push_prd_acr:
        type: boolean
        default: false

jobs:
  test:
    strategy:
      matrix:
        shard: [1/3, 2/3, 3/3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup node and dependency cache
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: extensions/real-estate/front-end/Web/package-lock.json
          registry-url: "https://npm.pkg.github.com"
          always-auth: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      - run: npm ci
        working-directory: extensions/real-estate/front-end/Web/
      - uses: actions/cache@v3
        with:
          path: /tmp/jest_rt
          key: ${{ hashFiles('**/package-lock.json') }}-${{ matrix.shard }}

      - name: Run tests
        run: npm run test -- --maxWorkers=100% --shard=${{ matrix.shard }}
        working-directory: extensions/real-estate/front-end/Web/