SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Metrics](
	[Id] [uniqueidentifier] NOT NULL,
	[ParentId] [uniqueidentifier] NULL,
	[Key] [nvarchar](64) NOT NULL,
	[Name] [nvarchar](128) NOT NULL,
	[Unit] [nvarchar](64) NOT NULL,
 CONSTRAINT [PK_Metrics] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Metrics]  WITH CHECK ADD  CONSTRAINT [FK_Metrics_Metrics] FOREIGN KEY([ParentId])
REFERENCES [dbo].[Metrics] ([Id])
GO

ALTER TABLE [dbo].[Metrics] CHECK CONSTRAINT [FK_Metrics_Metrics]
GO

CREATE UNIQUE NONCLUSTERED INDEX [UX_ParentId_Key] ON [dbo].[Metrics]
(
	[ParentId] ASC,
	[Key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


CREATE TABLE [dbo].[SiteMetricValues](
	[Id] [uniqueidentifier] NOT NULL,
	[SiteId] [uniqueidentifier] NOT NULL,
	[MetricId] [uniqueidentifier] NOT NULL,
	[Value] [decimal](15, 4) NOT NULL,
	[TimeStamp] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_SiteMetricValues] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SiteMetricValues]  WITH CHECK ADD  CONSTRAINT [FK_SiteMetricValues_Metrics] FOREIGN KEY([MetricId])
REFERENCES [dbo].[Metrics] ([Id])
GO

ALTER TABLE [dbo].[SiteMetricValues] CHECK CONSTRAINT [FK_SiteMetricValues_Metrics]
GO

ALTER TABLE [dbo].[SiteMetricValues]  WITH CHECK ADD  CONSTRAINT [FK_SiteMetricValues_Sites] FOREIGN KEY([SiteId])
REFERENCES [dbo].[Sites] ([Id])
GO

ALTER TABLE [dbo].[SiteMetricValues] CHECK CONSTRAINT [FK_SiteMetricValues_Sites]
GO

CREATE UNIQUE NONCLUSTERED INDEX [UX_SiteId_MetricId_TimeStamp] ON [dbo].[SiteMetricValues]
(
	[SiteId] ASC,
	[MetricId] ASC,
	[TimeStamp] DESC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_SiteId_TimeStamp] ON [dbo].[SiteMetricValues]
(
	[SiteId] ASC,
	[TimeStamp] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_TimeStamp] ON [dbo].[SiteMetricValues]
(
	[TimeStamp] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
