IF NOT EXISTS(SELECT 1
  FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME = 'Widgets'
   AND TABLE_SCHEMA = 'dbo'
   AND COLUMN_NAME = 'Metadata'
   AND CHARACTER_MAXIMUM_LENGTH = -1) -- (CHARACTER_MAXIMUM_LENGTH == -1) == MAX
BEGIN
ALTER TABLE [dbo].[Widgets] ALTER COLUMN Metadata nvarchar(max) not null
END
